name = "findabuse-proxy"
main = "src/index.ts"
compatibility_date = "2023-12-18"
account_id = "b0d7b9f87b57470ef508f1a511093cae"
routes = [
    { pattern = "api.findabuse.email/*", zone_name = "findabuse.email" },
]